# Advanced Functionality

In [1]:
# Import Library
import pandas as pd
import numpy as np

In [13]:
# Load Dataframe Coffee

coffee = pd.read_csv('data/coffee_update.csv')
bios = pd.read_csv('data/bios.csv')

In [14]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso   15.000000   3.99    99.75
1     Monday       Latte   15.000000   5.99    89.85
2    Tuesday    Espresso   21.666667   3.99   119.70
3    Tuesday       Latte   28.333333   5.99   119.80
4  Wednesday    Espresso   35.000000   3.99   139.65

### Fungsi .shift()
Secara sederhana, fungsi ini digunakan untuk menggeser data ke atas atau ke bawah pada indeks tertentu.

In [15]:
# test fungsi .shift()

# membuat kolom baru dengan isi pendapatan kemarin 

coffee['yesterday_revenue'] = coffee['revenue'].shift(2)

In [16]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue  yesterday_revenue
0     Monday    Espresso   15.000000   3.99    99.75                NaN
1     Monday       Latte   15.000000   5.99    89.85                NaN
2    Tuesday    Espresso   21.666667   3.99   119.70              99.75
3    Tuesday       Latte   28.333333   5.99   119.80              89.85
4  Wednesday    Espresso   35.000000   3.99   139.65             119.70

In [17]:
# membuat pertumbuhan persen

coffee['pct_change'] = coffee['revenue'] / coffee['yesterday_revenue'] * 100

In [18]:
coffee

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change
0,Monday,Espresso,15.000000,3.99,99.75,NaN,NaN
1,Monday,Latte,15.000000,5.99,89.85,NaN,NaN
2,Tuesday,Espresso,21.666667,3.99,119.70,99.75,120.000000
3,Tuesday,Latte,28.333333,5.99,119.80,89.85,133.333333
4,Wednesday,Espresso,35.000000,3.99,139.65,119.70,116.666667
5,Wednesday,Latte,25.000000,5.99,149.75,119.80,125.000000
6,Thursday,Espresso,40.000000,3.99,159.60,139.65,114.285714
7,Thursday,Latte,30.000000,5.99,179.70,149.75,120.000000
8,Friday,Espresso,45.000000,3.99,179.55,159.60,112.500000
9,Friday,Latte,35.000000,5.99,209.65,179.70,116.666667
10,Saturday,Espresso,45.000000,3.99,179.55,179.55,100.000000
11,Saturday,Latte,35.000000,5.99,209.65,209.65,100.000000
12,Sunday,Espresso,45.000000,3.99,179.55,179.55,100.000000
13,Sunday,Latte,35.000000,5.99,209.65,209.65,100.000000

### Fungsi .rank()
Fungsi ini digunakan untuk memberikan peringkat atau posisi pada setiap elemen dalam kumpulan data.

In [20]:
# contoh fungsi .rank()

# menerapkan rank dari tinggi suatu atlet 
bios['height_rank'] = bios['height_cm'].rank(ascending=False)

In [ ]:
menerapkan sort values dari terbesar ke terkecil
bios.sort_values(['height_rank'])

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_rank
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN,1.0
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN,2.5
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN,2.5
120266,122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN,5.0
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN,5.0
...,...,...,...,...,...,...,...,...,...,...,...
145490,149217,Sin Ye-Chan,1995-06-13,NaN,NaN,NaN,Republic of Korea,NaN,NaN,NaN,NaN
145491,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN,NaN
145492,149219,Carlos García-Ordóñez,1927-04-24,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,NaN,NaN,2019-11-24,NaN
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,NaN

In [23]:
# menampilkan 10 sample dengan mengambil kolom nama dan rank
bios.sort_values(['height_rank']).sample(10)[['name','height_rank']]

                    name  height_rank
139578      Imogen Grant      83975.0
128557   Andrea Klikovac      38677.0
78189      Austin Menaul      46966.0
78913      Grace Muneene      77037.5
29040       Marie Kibler          NaN
6772      Baek Jeong-Nam          NaN
96479   Ulrich Schindler      38677.0
125856        Morten Ask      21202.5
2410        Jordi Arrese      58380.5
20427       Zhu Qingyuan      83975.0

### Fungsi .rolling()
.rolling() adalah tentang melihat gambaran besar melalui "jendela" yang bergerak.

In [24]:
# menggunakan fungi .rolling()

coffee['cumulative_revenue'] = coffee['revenue'].cumsum()

In [25]:
coffee

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change,cumulative_revenue
0,Monday,Espresso,15.000000,3.99,99.75,NaN,NaN,99.75
1,Monday,Latte,15.000000,5.99,89.85,NaN,NaN,189.60
2,Tuesday,Espresso,21.666667,3.99,119.70,99.75,120.000000,309.30
3,Tuesday,Latte,28.333333,5.99,119.80,89.85,133.333333,429.10
4,Wednesday,Espresso,35.000000,3.99,139.65,119.70,116.666667,568.75
5,Wednesday,Latte,25.000000,5.99,149.75,119.80,125.000000,718.50
6,Thursday,Espresso,40.000000,3.99,159.60,139.65,114.285714,878.10
7,Thursday,Latte,30.000000,5.99,179.70,149.75,120.000000,1057.80
8,Friday,Espresso,45.000000,3.99,179.55,159.60,112.500000,1237.35
9,Friday,Latte,35.000000,5.99,209.65,179.70,116.666667,1447.00
10,Saturday,Espresso,45.000000,3.99,179.55,179.55,100.000000,1626.55
11,Saturday,Latte,35.000000,5.99,209.65,209.65,100.000000,1836.20
12,Sunday,Espresso,45.000000,3.99,179.55,179.55,100.000000,2015.75
13,Sunday,Latte,35.000000,5.99,209.65,209.65,100.000000,2225.40

In [27]:
# meng copy data hanya berisi tipe kopi latte dan menghtung kumulatif pendapatan nya per 3 hari menggunakan rolling

latte = coffee[coffee['Coffee Type'] == "Latte"].copy()
latte

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change,cumulative_revenue
1,Monday,Latte,15.000000,5.99,89.85,NaN,NaN,189.6
3,Tuesday,Latte,28.333333,5.99,119.80,89.85,133.333333,429.1
5,Wednesday,Latte,25.000000,5.99,149.75,119.80,125.000000,718.5
7,Thursday,Latte,30.000000,5.99,179.70,149.75,120.000000,1057.8
9,Friday,Latte,35.000000,5.99,209.65,179.70,116.666667,1447.0
11,Saturday,Latte,35.000000,5.99,209.65,209.65,100.000000,1836.2
13,Sunday,Latte,35.000000,5.99,209.65,209.65,100.000000,2225.4

In [28]:
latte['3day'] = latte['Units Sold'].rolling(3).sum()

In [29]:
latte

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change,cumulative_revenue,3day
1,Monday,Latte,15.000000,5.99,89.85,NaN,NaN,189.6,NaN
3,Tuesday,Latte,28.333333,5.99,119.80,89.85,133.333333,429.1,NaN
5,Wednesday,Latte,25.000000,5.99,149.75,119.80,125.000000,718.5,68.333333
7,Thursday,Latte,30.000000,5.99,179.70,149.75,120.000000,1057.8,83.333333
9,Friday,Latte,35.000000,5.99,209.65,179.70,116.666667,1447.0,90.000000
11,Saturday,Latte,35.000000,5.99,209.65,209.65,100.000000,1836.2,100.000000
13,Sunday,Latte,35.000000,5.99,209.65,209.65,100.000000,2225.4,105.000000