# Filtering Data | Syntax Operations, Numeric Values, Multiple Conditions

In [1]:
import pandas as pd

In [2]:
bios = pd.read_csv('data/bios.csv')

In [3]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [4]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [5]:
# memfilter tinggi dan mengambil kolom yang diinginkan saja
bios.loc[bios['height_cm'] > 220, ['height_cm', 'name', 'born_country']]

        height_cm             name born_country
5673        221.0   Gunther Behnke          GER
5781        223.0   Tommy Burleson          USA
6978        223.0  Arvydas Sabonis          LTU
89070       226.0         Yao Ming          CHN
89075       221.0   Roberto Dueñas          ESP
120266      221.0     Zhang Zhaoxu          CHN

In [6]:
# cara lain
bios[bios['height_cm'] > 200][['height_cm','name']]

        height_cm                name
1080        208.0      Bozhil Lozanov
1673        204.0    Alexis Rubalcaba
2647        203.0       Milan Šrejber
2827        206.0  Nik'oloz Deriugini
2832        205.0       Elşad Qadaşev
...           ...                 ...
143784      203.0  Daniel Miklasevich
143833      205.0  Garrett Muagututia
143834      201.0         Kyle Ensing
143835      203.0         Mitch Stahl
143919      204.0   Emerson Rodríguez

[1219 rows x 2 columns]

In [7]:
# jika terdapat 2 kondisi
bios[(bios['height_cm'] > 200) & (bios['born_country']=='USA')].sort_values(['height_cm'])

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
124688,127010,Dominic Breazeale,1985-08-24,Glendale,California,USA,United States,201.0,116.0,NaN
6376,6407,Jim King,1943-02-09,New Orleans,Louisiana,USA,United States,201.0,91.0,NaN
124339,126635,Steve Kasprzyk,1982-02-14,Willingboro,New Jersey,USA,United States,201.0,103.0,NaN
111805,113051,Deontay Wilder,1985-10-22,Tuscaloosa,Alabama,USA,United States,201.0,91.0,NaN
124433,126736,David Smith,1985-05-15,Panorama City,California,USA,United States,201.0,86.0,NaN
...,...,...,...,...,...,...,...,...,...,...
112319,113575,Chris Kaman,1982-04-28,Wyoming,Michigan,USA,Germany,213.0,122.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN

In [8]:
# mencari sebuah nama yang mengandung suatu kalimat yang kita inginkan misal "keith"

# mencari nama keith dengan case = false agar python tidak sensitif dengan angka kecil atau besar
bios[bios['name'].str.contains('keith', case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
117676,119195,Duncan Keith,1983-07-16,Winnipeg,Manitoba,CAN,Canada,185.0,88.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN
127310,129749,Tracy Keith-Matchitt,1990-03-30,Palmerston North,Manawatu-Wanganui,NZL,Cook Islands,167.0,60.0,NaN

In [9]:
# menggunakan sebuah pola pncarian regrex khusus fungsi .str
bios[bios['name'].str.contains('keith|patrick', case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
119,120,Patrick Wheatley,1899-01-20,Vryheid,KwaZulu-Natal,RSA,Great Britain,NaN,NaN,1967-11-05
319,320,Patrick De Koning,1961-04-23,Dendermonde,Oost-Vlaanderen,BEL,Belgium,178.0,92.0,NaN
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
2115,2125,Patrick Jopp,1962-01-08,NaN,NaN,NaN,Switzerland,176.0,67.0,NaN
...,...,...,...,...,...,...,...,...,...,...
143975,147633,Patrick Chinyemba,2001-01-03,NaN,NaN,NaN,Zambia,NaN,NaN,NaN
144172,147850,Patrick Jakob,1996-10-17,Sankt Johann in Tirol,Tirol,AUT,Austria,NaN,NaN,NaN
144547,148239,Patrick Galbraith,1986-03-11,Haderslev,Syddanmark,DEN,Denmark,NaN,NaN,NaN
144565,148257,Patrick Russell,1993-01-04,Gentofte,Hovedstaden,DEN,Denmark,186.0,93.0,NaN
145435,149158,Patrick Gasienica,1998-11-28,McHenry,Illinois,USA,United States,NaN,NaN,2023-06-12

In [10]:
# jika kita menonaktifkan pola pencarian regrex dalam fungsi .str
# bios[bios['name'].str.contains('keith|patrick', case=False, regex=False)]

In [11]:
# cara agar tidak mengulangi kata yang sama seperti bios lalu bios lagi terlihat aneh menggunakan sebuah filter modern agar kode telihat bersih dengan fungsi .query()

bios.query(('height_cm > 215' and 'born_country == "USA"'))

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145445,149168,Kristen Santos,1994-11-02,Fairfield,Connecticut,USA,United States,NaN,NaN,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN

In [12]:
bios[bios['born_country'].isin(['USA','GBR']) & (bios['name'].str.startswith("Keith",na=False))]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
14577,14674,Keith Harrison,1933-03-28,Birmingham,England,GBR,Great Britain,NaN,NaN,NaN
16166,16281,Keith Reynolds,1963-12-25,Solihull,England,GBR,Great Britain,173.0,68.0,NaN
18734,18862,Keith Sinclair,1945-06-26,Sunderland,England,GBR,Great Britain,190.0,79.0,NaN
29897,30123,Keith Langley,1961-06-03,Aldershot,England,GBR,Great Britain,173.0,70.0,NaN
34011,34275,Keith Remfry,1947-11-17,Ealing,England,GBR,Great Britain,193.0,114.0,2015-09-16
46885,47234,Keith Collin,1937-01-18,Marylebone,England,GBR,Great Britain,168.0,63.0,1991-03-06
50929,51288,Keith Carter,1924-08-30,Akron,Ohio,USA,United States,NaN,NaN,2013-05-03
51185,51544,Keith Russell,1948-01-15,Mesa,Arizona,USA,United States,188.0,73.0,NaN
52913,53288,Keith Erickson,1944-04-19,San Francisco,California,USA,United States,196.0,86.0,NaN
55317,55712,Keith Boxell,1958-05-06,Clapham,England,GBR,Great Britain,170.0,87.0,NaN
57818,58226,Keith Peache,1947-08-10,Lewisham,England,GBR,Great Britain,180.0,98.0,NaN
61748,62202,Keith Grogono,1912-11-04,Stratford,England,GBR,Great Britain,NaN,NaN,1999-03-22
62620,63086,Keith Musto,1936-01-12,Rochford,England,GBR,Great Britain,174.0,72.0,NaN
62678,63144,Keith Notary,1960-01-22,Merritt Island,Florida,USA,United States,170.0,66.0,NaN
68324,68841,Keith Angus,1943-04-05,Sheffield,England,GBR,Great Britain,170.0,59.0,NaN
68472,68989,Keith Cullen,1972-06-13,Ilford,England,GBR,Great Britain,177.0,61.0,NaN
68997,69514,Keith Stock,1957-03-18,Woolwich,England,GBR,Great Britain,176.0,73.0,NaN
77550,78141,Keith Brantly,1962-05-23,Scott Air Force Base,Illinois,USA,United States,180.0,64.0,NaN
84097,84766,Keith Christiansen,1944-07-14,International Falls,Minnesota,USA,United States,165.0,69.0,2018-11-05
94646,95413,Keith Meyer,1938-06-20,Geneva,Illinois,USA,United States,NaN,NaN,2010-07-25
95267,96037,Keith Oliver,1947-10-27,Liverpool,England,GBR,Great Britain,172.0,68.0,NaN
96452,97229,Keith Schellenberg,1929-03-13,Middlesbrough,England,GBR,Great Britain,NaN,NaN,2019-10-28
97499,98286,Keith Tkachuk,1972-03-28,Melrose,Massachusetts,USA,United States,188.0,102.0,NaN
98068,98860,Keith Wegeman,1929-08-28,Denver,Colorado,USA,United States,NaN,NaN,1974-08-22
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN

# Praktek

In [13]:
df_bios = pd.read_csv('data/bios.csv')

In [14]:
df_bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [15]:
# challenge level 1
# Cari semua atlet yang memiliki tinggi badan (height_cm) lebih dari 210 cm. Tampilkan hanya kolom name dan height_cm.

df_bios.loc[df_bios['height_cm'] > 210, ['name', 'height_cm']]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5572          Santiago Aldama      213.0
5583     Paulinho Villas Boas      217.0
5599        Vladimir Andreyev      215.0
5609          Franjo Arapović      211.0
...                       ...        ...
140298       Aaron Geramipoor      214.0
141018          Yuta Watanabe      215.0
142044          Jahlil Okafor      211.0
142930             Mike Tobey      213.0
143712           JaVale McGee      213.0

[150 rows x 2 columns]

In [16]:
# challenge level 2
# Cari atlet asal negara Perancis (born_country == 'FRA') yang memiliki berat badan (weight_kg) di bawah 60 kg.
df_bios.query(('born_country == "FRA"') and ('weight_kg < 60'))

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
14,15,Damien Éloi,1969-07-04,Vire,Calvados,FRA,France,165.0,58.0,NaN
49,50,Gillian Gowers,1964-04-09,NaN,NaN,NaN,Great Britain,157.0,55.0,NaN
62,63,Jo Muggeridge,1969-04-03,London,England,GBR,Great Britain,157.0,59.0,NaN
123,124,Steffi Graf,1969-06-14,Mannheim,Baden-Württemberg,GER,Germany West Germany,175.0,59.0,NaN
125,126,Anke Huber,1974-02-04,Bruchsal,Baden-Württemberg,GER,Germany,173.0,58.0,NaN
...,...,...,...,...,...,...,...,...,...,...
144807,148508,Arianna Valcepina,1994-05-09,Sondalo,Sondrio,ITA,Italy,170.0,56.0,NaN
145054,148766,Svetlana Mironova,1994-02-22,Moryakovsky Zaton,Tomsk,RUS,ROC,165.0,54.0,NaN
145055,148767,Kristina Reztsova,1996-04-27,Moskva (Moscow),Moskva,RUS,ROC,167.0,54.0,NaN
145243,148962,Veronika Machyniaková,1997-09-14,Brezno,Banská Bystrica,SVK,Slovakia,171.0,57.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN

In [17]:
# chalengge level 3
# Cari semua atlet yang namanya mengandung kata "William". Pastikan pencariannya tidak peka terhadap huruf besar/kecil (case-insensitive) dan tangani data kosong agar tidak error.

df_bios[df_bios['name'].str.contains("Williams", case=False, na=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
561,563,Hilda Williams,1876-01-01,Marton,England,GBR,Great Britain,NaN,NaN,1922-07-10
562,564,Alison Williamson,1971-11-03,Melton Mowbray,England,GBR,Great Britain,170.0,73.0,NaN
602,604,Jorge Williams,1904-08-07,Buenos Aires,Ciudad Autónoma de Buenos Aires,ARG,Argentina,NaN,NaN,1954-02-14
1320,1327,Zekaria Williams,1965-01-15,NaN,NaN,NaN,Cook Islands,160.0,51.0,NaN
1452,1459,Christa Williams,1978-02-08,Houston,Texas,USA,United States,172.0,72.0,NaN
...,...,...,...,...,...,...,...,...,...,...
143657,147311,Jack Williams,2000-04-22,NaN,NaN,NaN,United States,NaN,NaN,NaN
143686,147340,Micah Williams,2001-11-12,NaN,NaN,NaN,United States,NaN,NaN,NaN
143776,147432,Kevon Williams,1991-06-07,NaN,NaN,NaN,United States,NaN,NaN,NaN
144081,147747,Lynn Williams,1993-05-21,Fresno,California,USA,United States,NaN,NaN,NaN
145352,149075,Joshua Williamson,1996-08-29,Sanford,Florida,USA,United States,NaN,NaN,NaN

In [18]:
# challenge level 4
# Filter data atlet yang lahir di negara berikut: 'USA', 'CHN' (China), dan 'JPN' (Jepang).
df_bios[df_bios['born_country'].isin(["USA","CHN","JPN"])]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
83,84,Xinhua Chen,1960-01-30,Fuan,Fujian,CHN,Great Britain,175.0,71.0,NaN
133,134,Jie Schöpp,1968-01-25,Baoding,Hebei,CHN,Germany,174.0,63.0,NaN
381,382,He Ying,1977-04-17,Siping,Jilin,CHN,People's Republic of China,170.0,68.0,NaN
383,384,Ma Xiangjun,1964-10-30,Qingdao,Shandong,CHN,People's Republic of China,171.0,65.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN
145482,149209,Jiang Dongxu,1993-03-03,Harbin,Heilongjiang,CHN,People's Republic of China,NaN,NaN,NaN

In [19]:
# challenge level 5
# Tantangan: Cari atlet yang nama depannya diawali dengan huruf "Z". Gunakan metode regex untuk memastikan hanya mengecek bagian awal string.
df_bios[df_bios['name'].str.contains(r'^Z', regex=True, na=False)]  # POLA PENCARIAN REGEX

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
214,215,Zoltán Bátorfi,1975-07-20,Szombathely,Vas,HUN,Hungary,188.0,79.0,NaN
216,217,Zsolt Harczi,1967-02-17,Cegléd,Pest,HUN,Hungary,180.0,72.0,NaN
219,220,Zsolt Kriston,1961-02-12,Miskolc,Borsod-Abaúj-Zemplén,HUN,Hungary,185.0,76.0,NaN
238,239,Zelin Resiana,1972-07-09,Magelang,Jawa Tengah,INA,Indonesia,169.0,58.0,NaN
273,274,Zeeshan Ali,1970-01-01,Kolkata (Calcutta),West Bengal,IND,India,180.0,64.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145423,149146,Zachary DiGregorio,2001-11-14,West Medway,Massachusetts,USA,United States,NaN,NaN,NaN
145429,149152,Zoe Kalapos,1997-04-17,Detroit,Michigan,USA,United States,NaN,NaN,NaN
145475,149202,Zhou Xiaoyang,2002-09-24,NaN,NaN,NaN,People's Republic of China,NaN,NaN,NaN
145476,149203,Zhen Weijie,2003-10-16,NaN,NaN,NaN,People's Republic of China,NaN,NaN,NaN
145478,149205,Zhao Zihe,2000-07-29,NaN,NaN,NaN,People's Republic of China,NaN,NaN,NaN

In [20]:
# challenge level 6
# Gunakan fungsi .query() untuk mencari atlet yang lahir di wilayah (born_region) 'California' DAN kolom tanggal kematiannya (died_date) kosong (artinya atlet tersebut masih hidup atau tidak tercatat wafat).
died = df_bios['died_date'].isnull()
df_bios.query(('born_region == "California"') and ('@died'))

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
12,13,J. Defert,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN
13,14,Étienne Durand,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
145491,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN